"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Cuenta_1 = require("./Cuenta");
const Contador_1 = require("./Contador");
const Operation_1 = require("./Operation");
const Vehiculo_1 = require("./Vehiculo");
const cuenta = new Cuenta_1.Cuenta(0, "", ());
console.log(cuenta);
const operacion = new Operation_1.Operation(30, 20);
console.log(operacion.diff());
const counter = new Contador_1.Contador();
console.log(counter.counter);
counter.increment();
console.log(counter.counter);
counter.increment();
console.log(counter.counter);
counter.decrement();
console.log(counter.counter);
const vehiculo = new Vehiculo_1.Vehiculo("", "", 0, 0);
console.log(vehiculo);
